<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
} 
$options = array(
    'position'  => array(
        'type'  => 'select',
        'value' => 'position-left',
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => __('Position', '{vultur}'),
        'desc'  => __('Description', '{vultur}'),
        'choices' => array(
            'position-left' => __('Left', '{vultur}'),
            'position-left-button' => __('Left with Button', '{vultur}'),
            'position-center' => __('Center', '{vultur}'),
        ),
        'no-validate' => false,
    ),
    'color'  => array(
        'type'  => 'select',
        'value' => 'color-dark',
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => __('Color', '{vultur}'),
        'desc'  => __('Description', '{vultur}'),
        'choices' => array(
            'color-white' => __('Color White', '{vultur}'),
            'color-dark' => __('Color Dark', '{vultur}'),
        ),
        'no-validate' => false,
    ),
    'padding'  => array(
        'type'  => 'select',
        'value' => 'wrap-bg',
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => __('Wrap Padding', '{vultur}'),
        'desc'  => __('Description', '{vultur}'),
        'choices' => array(
            'wrap-bg' => __('Padding Large', '{vultur}'),
            'wrap-bg-small' => __('Padding Small', '{vultur}'),
        ),
        'no-validate' => false,
    ),
     'course_heading'  => array(
			'label' => esc_html__('Course Heading', 'vultur'),
			'type' => 'text',
			'value' => '',
			'desc' => esc_html__('', 'vultur'),
			), 	 
	 'course_sub_heading'  => array(
			'label' => esc_html__('Course Sub Heading', 'vultur'),
			'type' => 'text',
			'value' => '',
			'desc' => esc_html__('', 'vultur'),
			),
    'course_content'  => array(
        'label' => esc_html__('Course content', 'vultur'),
        'type' => 'wp-editor',
        'value' => '',
        'desc' => esc_html__('', 'vultur'),
        'media_buttons' => false,
        'wpautop' => true,
    ),
    'course_number'  => array(
			'label' => esc_html__('Show Number Of Course', 'vultur'),
			'type' => 'text',
			'value' => '',
			'desc' => esc_html__('', 'vultur'),
			),
    'short_content'  => array(
			'label' => esc_html__('Short the content', 'vultur'),
			'type' => 'text',
			'value' => '',
			'desc' => esc_html__('', 'vultur'),
			),
    'show_content'  => array(
        'type'  => 'checkbox',
        'value' => true,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Show Content', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Show the content', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'show_category'  => array(
        'type'  => 'checkbox',
        'value' => true,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Show Category', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Show the category', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'show_lessons'  => array(
        'type'  => 'checkbox',
        'value' => true,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Show Lessons', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Show the Lessons', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'show_student'  => array(
        'type'  => 'checkbox',
        'value' => true,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Show Student', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Show the Student', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'show_author'  => array(
        'type'  => 'checkbox',
        'value' => true,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Show Author', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Show the Author', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'show_price'  => array(
        'type'  => 'checkbox',
        'value' => true,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Show Price', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Show the Price', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'hide_meta_bottom'  => array(
        'type'  => 'checkbox',
        'value' => false,
        'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
        'label' => esc_html__('Hide Courses Meta Bottom', 'vultur'),
        'desc' => esc_html__('', 'vultur'),
        'help'  => __('Hide the meta bottom', 'vultur'),
        'text'  => __('Yes', 'vultur'),
    ),
    'button_text'  => array(
        'label' => esc_html__('Button Text', 'vultur'),
        'type' => 'text',
        'value' => '',
        'desc' => esc_html__('', 'vultur'),
    ),
    'button_link'  => array(
        'label' => esc_html__('Button Link', 'vultur'),
        'type' => 'text',
        'value' => '',
        'desc' => esc_html__('', 'vultur'),
    ),
    'layout' => array(
        'type'  => 'select',
        'label' => esc_html__('Select Courses Style','vultur'),
        'value' => esc_html__('layout1', 'vultur'),
        'choices' => array(
            'layout1' => esc_html__('Style 1 (3 Column)', 'vultur'),
            'layout2' => esc_html__('Style 2 (4 Column)', 'vultur'),
        ),
    ),
);